//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dominion.Resource_de_DE", typeof(Resource_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie hat zusätzliche Maßnahmen und kauft..
        /// </summary>
        internal static string ActionBuyMsg {
            get {
                return ResourceManager.GetString("ActionBuyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktionen.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  kaufte ein .
        /// </summary>
        internal static string Bought {
            get {
                return ResourceManager.GetString("Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bürokrat.
        /// </summary>
        internal static string Bureaucrat {
            get {
                return ResourceManager.GetString("Bureaucrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschaffen Sie sich einen Silber-Karte;. \nput sie oben auf dein Deck \nJedes anderen Spieler deckt ein Victory-Karte \nvon seiner Hand und legt sie auf seinem Deck \n (oder zeigt eine Hand ohne Victory-Karten)..
        /// </summary>
        internal static string BureaucratDesc {
            get {
                return ResourceManager.GetString("BureaucratDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setzen ein.
        /// </summary>
        internal static string BureaucratMsg1 {
            get {
                return ResourceManager.GetString("BureaucratMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück auf der Spitze ihrer Deck..
        /// </summary>
        internal static string BureaucratMsg2 {
            get {
                return ResourceManager.GetString("BureaucratMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie legte eine Silber auf dein Deck. Jeder andere Spieler deckt ein Victory-Karte und legt sie oben auf seinem Deck..
        /// </summary>
        internal static string BureaucratMsg3 {
            get {
                return ResourceManager.GetString("BureaucratMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kaufen.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie hat eine extra kaufen (s)..
        /// </summary>
        internal static string BuyMsg {
            get {
                return ResourceManager.GetString("BuyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kauft.
        /// </summary>
        internal static string Buys {
            get {
                return ResourceManager.GetString("Buys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keller.
        /// </summary>
        internal static string Cellar {
            get {
                return ResourceManager.GetString("Cellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Aktion \n Verwerfen beliebige Anzahl von Karten. \n +1 Karte pro Karte verworfen.
        /// </summary>
        internal static string CellarDesc {
            get {
                return ResourceManager.GetString("CellarDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entsorgen Sie eine beliebige Anzahl von Karten. +1 Karte pro Karte verworfen..
        /// </summary>
        internal static string CellarMsg {
            get {
                return ResourceManager.GetString("CellarMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundeskanzlerin.
        /// </summary>
        internal static string Chancellor {
            get {
                return ResourceManager.GetString("Chancellor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + 2 Währung \ nSie können sofort setzen Sie Ihre \n Deck in deinen Ablagestapel.
        /// </summary>
        internal static string ChancellorDesc {
            get {
                return ResourceManager.GetString("ChancellorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können Ihr Deck in deinen Ablagestapel legen..
        /// </summary>
        internal static string ChancellorMsg {
            get {
                return ResourceManager.GetString("ChancellorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapelle.
        /// </summary>
        internal static string Chapel {
            get {
                return ResourceManager.GetString("Chapel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash bis zu 4 Karten von deiner Hand.
        /// </summary>
        internal static string ChapelDesc {
            get {
                return ResourceManager.GetString("ChapelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up to 4 cards to trash from your hand..
        /// </summary>
        internal static string ChapelMsg {
            get {
                return ResourceManager.GetString("ChapelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie zum Spielbeginn.
        /// </summary>
        internal static string ClickToStart {
            get {
                return ResourceManager.GetString("ClickToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bestätigen.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupfer.
        /// </summary>
        internal static string Copper {
            get {
                return ResourceManager.GetString("Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Währung wert.
        /// </summary>
        internal static string CopperDesc {
            get {
                return ResourceManager.GetString("CopperDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratssaal.
        /// </summary>
        internal static string CouncilRoom {
            get {
                return ResourceManager.GetString("CouncilRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +4 Karten, +1 Buy zieht jeder andere Spieler eine Karte..
        /// </summary>
        internal static string CouncilRoomDesc {
            get {
                return ResourceManager.GetString("CouncilRoomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie hat 4 Karten und ein Kauf. Alle anderen bekamen, um 1 Karte zu ziehen..
        /// </summary>
        internal static string CouncilRoomMsg {
            get {
                return ResourceManager.GetString("CouncilRoomMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Währung.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluch.
        /// </summary>
        internal static string Curse {
            get {
                return ResourceManager.GetString("Curse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 Siegpunkt.
        /// </summary>
        internal static string CurseDesc {
            get {
                return ResourceManager.GetString("CurseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie auf Nicht Place Your Deck auf den Ablagestapel.
        /// </summary>
        internal static string DeckNotOnDiscard {
            get {
                return ResourceManager.GetString("DeckNotOnDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie, um dein Deck auf den Ablagestapel Zeigen.
        /// </summary>
        internal static string DeckOnDiscard {
            get {
                return ResourceManager.GetString("DeckOnDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verteidigt gegen den Angriff!.
        /// </summary>
        internal static string Defended {
            get {
                return ResourceManager.GetString("Defended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwerfen.
        /// </summary>
        internal static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwerfen Ausgewählte Karten.
        /// </summary>
        internal static string DiscardCards {
            get {
                return ResourceManager.GetString("DiscardCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicke, um eine Kupfer Verwerfen.
        /// </summary>
        internal static string DiscardCopper {
            get {
                return ResourceManager.GetString("DiscardCopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeigt Ihr: \n Aktionen, Buys, Währung, Gain-Betrag, und die aktuelle Schalten.
        /// </summary>
        internal static string Displays {
            get {
                return ResourceManager.GetString("Displays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie zeichnete Karten und bekam zusätzliche Aktionen und extra kauft..
        /// </summary>
        internal static string DrawActionBuyMsg {
            get {
                return ResourceManager.GetString("DrawActionBuyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie zeichnete Karten und bekam zusätzliche Aktionen..
        /// </summary>
        internal static string DrawActionMsg {
            get {
                return ResourceManager.GetString("DrawActionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie zog Karten..
        /// </summary>
        internal static string DrawMsg {
            get {
                return ResourceManager.GetString("DrawMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzogtum.
        /// </summary>
        internal static string Duchy {
            get {
                return ResourceManager.GetString("Duchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Siegpunkte.
        /// </summary>
        internal static string DuchyDesc {
            get {
                return ResourceManager.GetString("DuchyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endet der Aktionsphase, indem Sie in der Buy-Phase.
        /// </summary>
        internal static string EndActionPhase {
            get {
                return ResourceManager.GetString("EndActionPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endphase.
        /// </summary>
        internal static string EndPhase {
            get {
                return ResourceManager.GetString("EndPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende biegen.
        /// </summary>
        internal static string EndTurn {
            get {
                return ResourceManager.GetString("EndTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immobilien.
        /// </summary>
        internal static string Estate {
            get {
                return ResourceManager.GetString("Estate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Siegpunkt.
        /// </summary>
        internal static string EstateDesc {
            get {
                return ResourceManager.GetString("EstateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fest.
        /// </summary>
        internal static string Feast {
            get {
                return ResourceManager.GetString("Feast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash diese Karte und gewinnen Sie eine Karte kostet bis zu 5 Währung.
        /// </summary>
        internal static string FeastDesc {
            get {
                return ResourceManager.GetString("FeastDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimm dir eine Karte kostet bis zu 5 Münzen..
        /// </summary>
        internal static string FeastMsg {
            get {
                return ResourceManager.GetString("FeastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festspiele.
        /// </summary>
        internal static string Festival {
            get {
                return ResourceManager.GetString("Festival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Aktionen \n +1 \n buy \n +2 Währung.
        /// </summary>
        internal static string FestivalDesc {
            get {
                return ResourceManager.GetString("FestivalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewinnen.
        /// </summary>
        internal static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben noch Gewinne übrig, Einstellung wieder zu gewinnen..
        /// </summary>
        internal static string GainsLeft {
            get {
                return ResourceManager.GetString("GainsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gärten.
        /// </summary>
        internal static string Gardens {
            get {
                return ResourceManager.GetString("Gardens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Siegpunkt für je 10 Karten in deinem Deck (abgerundet)..
        /// </summary>
        internal static string GardensDesc {
            get {
                return ResourceManager.GetString("GardensDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fertig machen.
        /// </summary>
        internal static string GetReady {
            get {
                return ResourceManager.GetString("GetReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goldton.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Währung wert.
        /// </summary>
        internal static string GoldDesc {
            get {
                return ResourceManager.GetString("GoldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzlichen Glückwunsch, .
        /// </summary>
        internal static string Grats1 {
            get {
                return ResourceManager.GetString("Grats1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  zu gewinnen!.
        /// </summary>
        internal static string Grats2 {
            get {
                return ResourceManager.GetString("Grats2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsche Anzahl von Karten für die Miliz abgeworfen.
        /// </summary>
        internal static string IncorrectForMilitia {
            get {
                return ResourceManager.GetString("IncorrectForMilitia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ist bereit.
        /// </summary>
        internal static string IsReady {
            get {
                return ResourceManager.GetString("IsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor.
        /// </summary>
        internal static string Laboratory {
            get {
                return ResourceManager.GetString("Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Cards \n +1 Aktion.
        /// </summary>
        internal static string LaboratoryDesc {
            get {
                return ResourceManager.GetString("LaboratoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptfenster.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markt.
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Card \n +1 Aktion \n +1 Buy \n +1 Währung.
        /// </summary>
        internal static string MarketDesc {
            get {
                return ResourceManager.GetString("MarketDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bürgerwehr.
        /// </summary>
        internal static string Militia {
            get {
                return ResourceManager.GetString("Militia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Währung \nAlle anderen Spielern sofort verwerfen auf drei Karten..
        /// </summary>
        internal static string MilitiaDesc {
            get {
                return ResourceManager.GetString("MilitiaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andere Spieler mussten auf 3 Karten zu verwerfen..
        /// </summary>
        internal static string MilitiaMsg {
            get {
                return ResourceManager.GetString("MilitiaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bergwerk.
        /// </summary>
        internal static string Mine {
            get {
                return ResourceManager.GetString("Mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash einen Schatz Karte von deiner Hand \n Gewinnen eine Schatzkarte mit Kosten bis zu \n 3 Währung mehr, sondern setzen auf die Hand..
        /// </summary>
        internal static string MineDesc {
            get {
                return ResourceManager.GetString("MineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können wählen Sie eine Schatzkarte für eine Schatzkarte mit Kosten bis zu 3 weitere Papierkorb..
        /// </summary>
        internal static string MineMsg {
            get {
                return ResourceManager.GetString("MineMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vermissen Sie einen oder mehrere .
        /// </summary>
        internal static string MissingCards1 {
            get {
                return ResourceManager.GetString("MissingCards1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  von der Hand..
        /// </summary>
        internal static string MissingCards2 {
            get {
                return ResourceManager.GetString("MissingCards2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graben.
        /// </summary>
        internal static string Moat {
            get {
                return ResourceManager.GetString("Moat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Karten\nWenn ein anderer Spieler einen Angriff Karte spielt, können Sie diese aus der Hand zu offenbaren. Wenn Sie das tun, sind Sie unabhängig von diesem Angriff..
        /// </summary>
        internal static string MoatDesc {
            get {
                return ResourceManager.GetString("MoatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geldverleiher.
        /// </summary>
        internal static string Moneylender {
            get {
                return ResourceManager.GetString("Moneylender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash ein Kupfer aus deiner Hand. \n Wenn Sie tun +3 Währung.
        /// </summary>
        internal static string MoneylenderDesc {
            get {
                return ResourceManager.GetString("MoneylenderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash eine Kupfer Karte aus deiner Hand. Wenn Sie das tun, +3 Coins..
        /// </summary>
        internal static string MoneylenderMsg {
            get {
                return ResourceManager.GetString("MoneylenderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr als 4 Karten ausgewählt!.
        /// </summary>
        internal static string MoreThanFour {
            get {
                return ResourceManager.GetString("MoreThanFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Beendet ihrerseits. \n ======== \n.
        /// </summary>
        internal static string NextTurn {
            get {
                return ResourceManager.GetString("NextTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Gewinne in Spieler übrig.
        /// </summary>
        internal static string NoGainsLeft {
            get {
                return ResourceManager.GetString("NoGainsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie auf Nicht Verwerfen einer Kupfer.
        /// </summary>
        internal static string NotDiscardCopper {
            get {
                return ResourceManager.GetString("NotDiscardCopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht genug Währung für Gewinn. .
        /// </summary>
        internal static string NotEnoughCur {
            get {
                return ResourceManager.GetString("NotEnoughCur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht in Spieler zu gewinnen.
        /// </summary>
        internal static string NotGain {
            get {
                return ResourceManager.GetString("NotGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spielen.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spielt die ausgewählte Karte.
        /// </summary>
        internal static string PlayCards {
            get {
                return ResourceManager.GetString("PlayCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  spielte eine .
        /// </summary>
        internal static string Played {
            get {
                return ResourceManager.GetString("Played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prep Bildschirm.
        /// </summary>
        internal static string Prep {
            get {
                return ResourceManager.GetString("Prep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinz.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Siegpunkte.
        /// </summary>
        internal static string ProvinceDesc {
            get {
                return ResourceManager.GetString("ProvinceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renovieren.
        /// </summary>
        internal static string Remodel {
            get {
                return ResourceManager.GetString("Remodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash eine Karte aus deiner Hand. \n Verstärkung aa-Karte kostet bis zu 2 Währung \n mehr als die Papierkorb-Karte.
        /// </summary>
        internal static string RemodelDesc {
            get {
                return ResourceManager.GetString("RemodelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie eine Karte in den Papierkorb und renovieren. Dann wählen Sie eine Karte zu gewinnen..
        /// </summary>
        internal static string RemodelMsg {
            get {
                return ResourceManager.GetString("RemodelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ergab eine Hand ohne Sieg Karten..
        /// </summary>
        internal static string RevealNoVict {
            get {
                return ResourceManager.GetString("RevealNoVict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silber.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Währung Wert.
        /// </summary>
        internal static string SilverDesc {
            get {
                return ResourceManager.GetString("SilverDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schmiede.
        /// </summary>
        internal static string Smithy {
            get {
                return ResourceManager.GetString("Smithy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3 Karten.
        /// </summary>
        internal static string SmithyDesc {
            get {
                return ResourceManager.GetString("SmithyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitzel.
        /// </summary>
        internal static string Spy {
            get {
                return ResourceManager.GetString("Spy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Karte\n+1 Aktion\nReveal die oberste Karte jedes Spielers Deck, und entscheiden, ob es bleibt oder wird verworfen..
        /// </summary>
        internal static string SpyDesc {
            get {
                return ResourceManager.GetString("SpyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeder Spieler (auch Sie) deckt die oberste Karte seines Decks und entweder verwirft sie oder legt sie zurück, Ihre Wahl..
        /// </summary>
        internal static string SpyMsg {
            get {
                return ResourceManager.GetString("SpyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartenstapel leer war.
        /// </summary>
        internal static string StackEmpty {
            get {
                return ResourceManager.GetString("StackEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startbildschirm.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string TestString {
            get {
                return ResourceManager.GetString("TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieb.
        /// </summary>
        internal static string Thief {
            get {
                return ResourceManager.GetString("Thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeder andere Spieler deckt die obersten 2 Karten von seinem Deck\n Wenn sie irgendwelche Schatz Karten aufgedeckt, trash sie einer von ihnen, dass Sie sich entscheiden\nSie können gewinnen oder alle dieser Karten weggeworfen. Sie verwerfen die anderen aufgedeckten Karten..
        /// </summary>
        internal static string ThiefDesc {
            get {
                return ResourceManager.GetString("ThiefDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean: Choose if you want to gain an opponent&apos;s trashed treasure card.
        ///Wählen Sie, wenn Sie einen Gegner verwüstet Schatzkarte gewinnen wollen..
        /// </summary>
        internal static string ThiefMsg {
            get {
                return ResourceManager.GetString("ThiefMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ergab eine.
        /// </summary>
        internal static string ThiefMsg1 {
            get {
                return ResourceManager.GetString("ThiefMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  von der Spitze ihrer Deck..
        /// </summary>
        internal static string ThiefMsg2 {
            get {
                return ResourceManager.GetString("ThiefMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thronsaal.
        /// </summary>
        internal static string ThroneRoom {
            get {
                return ResourceManager.GetString("ThroneRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen und Aktion Karte in Ihrer Hand. \n Play it zweimal.
        /// </summary>
        internal static string ThroneRoomDesc {
            get {
                return ResourceManager.GetString("ThroneRoomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle eine Aktionskarte zweimal spielen..
        /// </summary>
        internal static string ThroneRoomMsg {
            get {
                return ResourceManager.GetString("ThroneRoomMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es war ein Unentschieden!.
        /// </summary>
        internal static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papierkorb.
        /// </summary>
        internal static string Trash {
            get {
                return ResourceManager.GetString("Trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papierkorb der ausgewählten Karte.
        /// </summary>
        internal static string TrashCards {
            get {
                return ResourceManager.GetString("TrashCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drehen.
        /// </summary>
        internal static string Turn {
            get {
                return ResourceManager.GetString("Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sieg.
        /// </summary>
        internal static string TypeString0 {
            get {
                return ResourceManager.GetString("TypeString0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schatz.
        /// </summary>
        internal static string TypeString1 {
            get {
                return ResourceManager.GetString("TypeString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktion.
        /// </summary>
        internal static string TypeString2 {
            get {
                return ResourceManager.GetString("TypeString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktion - Angriff.
        /// </summary>
        internal static string TypeString3 {
            get {
                return ResourceManager.GetString("TypeString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktion - Reaktion.
        /// </summary>
        internal static string TypeString4 {
            get {
                return ResourceManager.GetString("TypeString4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie auf &quot;Upgrade&quot; Währung.
        /// </summary>
        internal static string UpgradeCur {
            get {
                return ResourceManager.GetString("UpgradeCur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hatte .
        /// </summary>
        internal static string VictPts1 {
            get {
                return ResourceManager.GetString("VictPts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Siegpunkte. \n.
        /// </summary>
        internal static string VictPts2 {
            get {
                return ResourceManager.GetString("VictPts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dorf.
        /// </summary>
        internal static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Card \n +2 Aktionen.
        /// </summary>
        internal static string VillageDesc {
            get {
                return ResourceManager.GetString("VillageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War ein renovieren. Wird er auf die nächste Karte Papierkorb..
        /// </summary>
        internal static string WasRemodel {
            get {
                return ResourceManager.GetString("WasRemodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexe.
        /// </summary>
        internal static string Witch {
            get {
                return ResourceManager.GetString("Witch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Karten. \n Jeder Mitspieler bekommt einen Fluch Karte..
        /// </summary>
        internal static string WitchDesc {
            get {
                return ResourceManager.GetString("WitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie zog 2 Karten und gab jedem Flüche..
        /// </summary>
        internal static string WitchMsg {
            get {
                return ResourceManager.GetString("WitchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holzfäller.
        /// </summary>
        internal static string Woodcutter {
            get {
                return ResourceManager.GetString("Woodcutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Buy \ n +2 Währungen.
        /// </summary>
        internal static string WoodcutterDesc {
            get {
                return ResourceManager.GetString("WoodcutterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkstatt.
        /// </summary>
        internal static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimm dir eine Karte mit Kosten bis zu 4 Währung.
        /// </summary>
        internal static string WorkshopDesc {
            get {
                return ResourceManager.GetString("WorkshopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimm dir eine Karte kostet bis zu 4 Münzen..
        /// </summary>
        internal static string WorkshopMsg {
            get {
                return ResourceManager.GetString("WorkshopMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
