//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dominion.Resource_de_DE", typeof(Resource_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bürokrat.
        /// </summary>
        internal static string Bureaucrat {
            get {
                return ResourceManager.GetString("Bureaucrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschaffen Sie sich einen Silber-Karte;. \nput sie oben auf dein Deck \nJedes anderen Spieler deckt ein Victory-Karte \nvon seiner Hand und legt sie auf seinem Deck \n (oder zeigt eine Hand ohne Victory-Karten)..
        /// </summary>
        internal static string BureaucratDesc {
            get {
                return ResourceManager.GetString("BureaucratDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keller.
        /// </summary>
        internal static string Cellar {
            get {
                return ResourceManager.GetString("Cellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Aktion \n Verwerfen beliebige Anzahl von Karten. \n +1 Karte pro Karte verworfen.
        /// </summary>
        internal static string CellarDesc {
            get {
                return ResourceManager.GetString("CellarDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundeskanzlerin.
        /// </summary>
        internal static string Chancellor {
            get {
                return ResourceManager.GetString("Chancellor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + 2 Währung \ nSie können sofort setzen Sie Ihre \n Deck in deinen Ablagestapel.
        /// </summary>
        internal static string ChancellorDesc {
            get {
                return ResourceManager.GetString("ChancellorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapelle.
        /// </summary>
        internal static string Chapel {
            get {
                return ResourceManager.GetString("Chapel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash bis zu 4 Karten von deiner Hand.
        /// </summary>
        internal static string ChapelDesc {
            get {
                return ResourceManager.GetString("ChapelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupfer.
        /// </summary>
        internal static string Copper {
            get {
                return ResourceManager.GetString("Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Währung wert.
        /// </summary>
        internal static string CopperDesc {
            get {
                return ResourceManager.GetString("CopperDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratssaal.
        /// </summary>
        internal static string CouncilRoom {
            get {
                return ResourceManager.GetString("CouncilRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +4 Karten, +1 Buy zieht jeder andere Spieler eine Karte..
        /// </summary>
        internal static string CouncilRoomDesc {
            get {
                return ResourceManager.GetString("CouncilRoomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluch.
        /// </summary>
        internal static string Curse {
            get {
                return ResourceManager.GetString("Curse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 Siegpunkt.
        /// </summary>
        internal static string CurseDesc {
            get {
                return ResourceManager.GetString("CurseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzogtum.
        /// </summary>
        internal static string Duchy {
            get {
                return ResourceManager.GetString("Duchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Siegpunkte.
        /// </summary>
        internal static string DuchyDesc {
            get {
                return ResourceManager.GetString("DuchyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immobilien.
        /// </summary>
        internal static string Estate {
            get {
                return ResourceManager.GetString("Estate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Siegpunkt.
        /// </summary>
        internal static string EstateDesc {
            get {
                return ResourceManager.GetString("EstateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fest.
        /// </summary>
        internal static string Feast {
            get {
                return ResourceManager.GetString("Feast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash diese Karte und gewinnen Sie eine Karte kostet bis zu 5 Währung.
        /// </summary>
        internal static string FeastDesc {
            get {
                return ResourceManager.GetString("FeastDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival.
        /// </summary>
        internal static string Festival {
            get {
                return ResourceManager.GetString("Festival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Aktionen \n +1 \n buy \n +2 Währung.
        /// </summary>
        internal static string FestivalDesc {
            get {
                return ResourceManager.GetString("FestivalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardens.
        /// </summary>
        internal static string Gardens {
            get {
                return ResourceManager.GetString("Gardens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Siegpunkt für je 10 Karten in deinem Deck (abgerundet)..
        /// </summary>
        internal static string GardensDesc {
            get {
                return ResourceManager.GetString("GardensDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Währung wert.
        /// </summary>
        internal static string GoldDesc {
            get {
                return ResourceManager.GetString("GoldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory.
        /// </summary>
        internal static string Laboratory {
            get {
                return ResourceManager.GetString("Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Cards \n +1 Aktion.
        /// </summary>
        internal static string LaboratoryDesc {
            get {
                return ResourceManager.GetString("LaboratoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markt.
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Card \n +1 Aktion \n +1 Buy \n +1 Währung.
        /// </summary>
        internal static string MarketDesc {
            get {
                return ResourceManager.GetString("MarketDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Militia.
        /// </summary>
        internal static string Militia {
            get {
                return ResourceManager.GetString("Militia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Währung \nAlle anderen Spielern sofort verwerfen auf drei Karten..
        /// </summary>
        internal static string MilitiaDesc {
            get {
                return ResourceManager.GetString("MilitiaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bergwerk.
        /// </summary>
        internal static string Mine {
            get {
                return ResourceManager.GetString("Mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash einen Schatz Karte von deiner Hand \n Gewinnen eine Schatzkarte mit Kosten bis zu \n 3 Währung mehr, sondern setzen auf die Hand..
        /// </summary>
        internal static string MineDesc {
            get {
                return ResourceManager.GetString("MineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geldverleiher.
        /// </summary>
        internal static string Moneylender {
            get {
                return ResourceManager.GetString("Moneylender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash ein Kupfer aus deiner Hand. \n Wenn Sie tun +3 Währung.
        /// </summary>
        internal static string MoneylenderDesc {
            get {
                return ResourceManager.GetString("MoneylenderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinz.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Siegpunkte.
        /// </summary>
        internal static string ProvinceDesc {
            get {
                return ResourceManager.GetString("ProvinceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renovieren.
        /// </summary>
        internal static string Remodel {
            get {
                return ResourceManager.GetString("Remodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash eine Karte aus deiner Hand. \n Verstärkung aa-Karte kostet bis zu 2 Währung \n mehr als die Papierkorb-Karte.
        /// </summary>
        internal static string RemodelDesc {
            get {
                return ResourceManager.GetString("RemodelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silber.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Währung Wert.
        /// </summary>
        internal static string SilverDesc {
            get {
                return ResourceManager.GetString("SilverDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schmiede.
        /// </summary>
        internal static string Smithy {
            get {
                return ResourceManager.GetString("Smithy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3 Karten.
        /// </summary>
        internal static string SmithyDesc {
            get {
                return ResourceManager.GetString("SmithyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitzel.
        /// </summary>
        internal static string Spy {
            get {
                return ResourceManager.GetString("Spy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Karte\n+1 Aktion\nReveal die oberste Karte jedes Spielers Deck, und entscheiden, ob es bleibt oder wird verworfen..
        /// </summary>
        internal static string SpyDesc {
            get {
                return ResourceManager.GetString("SpyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string TestString {
            get {
                return ResourceManager.GetString("TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieb.
        /// </summary>
        internal static string Thief {
            get {
                return ResourceManager.GetString("Thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeder andere Spieler deckt die obersten 2 Karten von seinem Deck\n Wenn sie irgendwelche Schatz Karten aufgedeckt, trash sie einer von ihnen, dass Sie sich entscheiden\nSie können gewinnen oder alle dieser Karten weggeworfen. Sie verwerfen die anderen aufgedeckten Karten..
        /// </summary>
        internal static string ThiefDesc {
            get {
                return ResourceManager.GetString("ThiefDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thronsaal.
        /// </summary>
        internal static string ThroneRoom {
            get {
                return ResourceManager.GetString("ThroneRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen und Aktion Karte in Ihrer Hand. \n Play it zweimal.
        /// </summary>
        internal static string ThroneRoomDesc {
            get {
                return ResourceManager.GetString("ThroneRoomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dorf.
        /// </summary>
        internal static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Card \n +2 Aktionen.
        /// </summary>
        internal static string VillageDesc {
            get {
                return ResourceManager.GetString("VillageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexe.
        /// </summary>
        internal static string Witch {
            get {
                return ResourceManager.GetString("Witch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Karten. \n Jeder Mitspieler bekommt einen Fluch Karte..
        /// </summary>
        internal static string WitchDesc {
            get {
                return ResourceManager.GetString("WitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holzfäller.
        /// </summary>
        internal static string Woodcutter {
            get {
                return ResourceManager.GetString("Woodcutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Buy \ n +2 Währungen.
        /// </summary>
        internal static string WoodcutterDesc {
            get {
                return ResourceManager.GetString("WoodcutterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkstatt.
        /// </summary>
        internal static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimm dir eine Karte mit Kosten bis zu 4 Währung.
        /// </summary>
        internal static string WorkshopDesc {
            get {
                return ResourceManager.GetString("WorkshopDesc", resourceCulture);
            }
        }
    }
}
