//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dominion.Resource_en_US", typeof(Resource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  bought a .
        /// </summary>
        internal static string Bought {
            get {
                return ResourceManager.GetString("Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bureaucrat.
        /// </summary>
        internal static string Bureaucrat {
            get {
                return ResourceManager.GetString("Bureaucrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain a Silver card;\nput it on top of your deck.\nEach other player reveals a Victory card\nfrom his hand and puts it on his deck\n(or reveals a hand with no Victory cards)..
        /// </summary>
        internal static string BureaucratDesc {
            get {
                return ResourceManager.GetString("BureaucratDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  put a .
        /// </summary>
        internal static string BureaucratMsg1 {
            get {
                return ResourceManager.GetString("BureaucratMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  back on the top of their deck..
        /// </summary>
        internal static string BureaucratMsg2 {
            get {
                return ResourceManager.GetString("BureaucratMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellar.
        /// </summary>
        internal static string Cellar {
            get {
                return ResourceManager.GetString("Cellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Action\nDiscard any number of cards.\n+1 Card per card discarded.
        /// </summary>
        internal static string CellarDesc {
            get {
                return ResourceManager.GetString("CellarDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chancellor.
        /// </summary>
        internal static string Chancellor {
            get {
                return ResourceManager.GetString("Chancellor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + 2 currency\nYou may immediatly put your\ndeck into your discard pile.
        /// </summary>
        internal static string ChancellorDesc {
            get {
                return ResourceManager.GetString("ChancellorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapel.
        /// </summary>
        internal static string Chapel {
            get {
                return ResourceManager.GetString("Chapel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash up to 4 cards from your hand.
        /// </summary>
        internal static string ChapelDesc {
            get {
                return ResourceManager.GetString("ChapelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper.
        /// </summary>
        internal static string Copper {
            get {
                return ResourceManager.GetString("Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Currency Value.
        /// </summary>
        internal static string CopperDesc {
            get {
                return ResourceManager.GetString("CopperDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Council Room.
        /// </summary>
        internal static string CouncilRoom {
            get {
                return ResourceManager.GetString("CouncilRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +4 Cards, +1 Buy, Each other player draws a card..
        /// </summary>
        internal static string CouncilRoomDesc {
            get {
                return ResourceManager.GetString("CouncilRoomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curse.
        /// </summary>
        internal static string Curse {
            get {
                return ResourceManager.GetString("Curse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 Victory Point.
        /// </summary>
        internal static string CurseDesc {
            get {
                return ResourceManager.GetString("CurseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defended against the attack!.
        /// </summary>
        internal static string Defended {
            get {
                return ResourceManager.GetString("Defended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duchy.
        /// </summary>
        internal static string Duchy {
            get {
                return ResourceManager.GetString("Duchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Victory Points.
        /// </summary>
        internal static string DuchyDesc {
            get {
                return ResourceManager.GetString("DuchyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estate.
        /// </summary>
        internal static string Estate {
            get {
                return ResourceManager.GetString("Estate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Victory Point.
        /// </summary>
        internal static string EstateDesc {
            get {
                return ResourceManager.GetString("EstateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feast.
        /// </summary>
        internal static string Feast {
            get {
                return ResourceManager.GetString("Feast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash this card and gain a card costing up to 5 Currency.
        /// </summary>
        internal static string FeastDesc {
            get {
                return ResourceManager.GetString("FeastDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival.
        /// </summary>
        internal static string Festival {
            get {
                return ResourceManager.GetString("Festival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Actions\n+1\nBuy\n+2 Currency.
        /// </summary>
        internal static string FestivalDesc {
            get {
                return ResourceManager.GetString("FestivalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still have gains left, setting to gain again..
        /// </summary>
        internal static string GainsLeft {
            get {
                return ResourceManager.GetString("GainsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardens.
        /// </summary>
        internal static string Gardens {
            get {
                return ResourceManager.GetString("Gardens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worth 1 Victory Point for every 10 cards in your deck (rounded down)..
        /// </summary>
        internal static string GardensDesc {
            get {
                return ResourceManager.GetString("GardensDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Currency Value.
        /// </summary>
        internal static string GoldDesc {
            get {
                return ResourceManager.GetString("GoldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, .
        /// </summary>
        internal static string Grats1 {
            get {
                return ResourceManager.GetString("Grats1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on winning!.
        /// </summary>
        internal static string Grats2 {
            get {
                return ResourceManager.GetString("Grats2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of cards discarded for the Militia effect.
        /// </summary>
        internal static string IncorrectForMilitia {
            get {
                return ResourceManager.GetString("IncorrectForMilitia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory.
        /// </summary>
        internal static string Laboratory {
            get {
                return ResourceManager.GetString("Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Cards\n+1 Action.
        /// </summary>
        internal static string LaboratoryDesc {
            get {
                return ResourceManager.GetString("LaboratoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Card\n+1 Action\n+1 Buy\n+1 Currency.
        /// </summary>
        internal static string MarketDesc {
            get {
                return ResourceManager.GetString("MarketDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Militia.
        /// </summary>
        internal static string Militia {
            get {
                return ResourceManager.GetString("Militia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Currency\nAll other players immediately discard down to three cards..
        /// </summary>
        internal static string MilitiaDesc {
            get {
                return ResourceManager.GetString("MilitiaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine.
        /// </summary>
        internal static string Mine {
            get {
                return ResourceManager.GetString("Mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash a Treasure card from your hand\nGain a Treasure card costing up to\n 3 Currency more; put it into your hand..
        /// </summary>
        internal static string MineDesc {
            get {
                return ResourceManager.GetString("MineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing one or more .
        /// </summary>
        internal static string MissingCards1 {
            get {
                return ResourceManager.GetString("MissingCards1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from hand..
        /// </summary>
        internal static string MissingCards2 {
            get {
                return ResourceManager.GetString("MissingCards2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moat.
        /// </summary>
        internal static string Moat {
            get {
                return ResourceManager.GetString("Moat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Cards\nWhen another player plays an Attack card, you may reveal this from your hand. If you do, you are unaffected by that Attack..
        /// </summary>
        internal static string MoatDesc {
            get {
                return ResourceManager.GetString("MoatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneylender.
        /// </summary>
        internal static string Moneylender {
            get {
                return ResourceManager.GetString("Moneylender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash a copper from your hand.\nIf you do +3 Currency.
        /// </summary>
        internal static string MoneylenderDesc {
            get {
                return ResourceManager.GetString("MoneylenderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 4 cards selected!.
        /// </summary>
        internal static string MoreThanFour {
            get {
                return ResourceManager.GetString("MoreThanFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ended their turn.\n========\n.
        /// </summary>
        internal static string NextTurn {
            get {
                return ResourceManager.GetString("NextTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gains left in player.
        /// </summary>
        internal static string NoGainsLeft {
            get {
                return ResourceManager.GetString("NoGainsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough currency for gain. .
        /// </summary>
        internal static string NotEnoughCur {
            get {
                return ResourceManager.GetString("NotEnoughCur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not gain in player.
        /// </summary>
        internal static string NotGain {
            get {
                return ResourceManager.GetString("NotGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  played a .
        /// </summary>
        internal static string Played {
            get {
                return ResourceManager.GetString("Played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Victory Points.
        /// </summary>
        internal static string ProvinceDesc {
            get {
                return ResourceManager.GetString("ProvinceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remodel.
        /// </summary>
        internal static string Remodel {
            get {
                return ResourceManager.GetString("Remodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash a card from your hand.\nGain a a card costing up to 2 Currency\nmore than the trashed card.
        /// </summary>
        internal static string RemodelDesc {
            get {
                return ResourceManager.GetString("RemodelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  revealed a hand with no victory cards..
        /// </summary>
        internal static string RevealNoVict {
            get {
                return ResourceManager.GetString("RevealNoVict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Currency Value.
        /// </summary>
        internal static string SilverDesc {
            get {
                return ResourceManager.GetString("SilverDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smithy.
        /// </summary>
        internal static string Smithy {
            get {
                return ResourceManager.GetString("Smithy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3 Cards.
        /// </summary>
        internal static string SmithyDesc {
            get {
                return ResourceManager.GetString("SmithyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spy.
        /// </summary>
        internal static string Spy {
            get {
                return ResourceManager.GetString("Spy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Card\n+1 Action\nReveal the top card of each player&apos;s deck, and choose whether it stays or is discarded..
        /// </summary>
        internal static string SpyDesc {
            get {
                return ResourceManager.GetString("SpyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Stack was Empty.
        /// </summary>
        internal static string StackEmpty {
            get {
                return ResourceManager.GetString("StackEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the test string!.
        /// </summary>
        internal static string TestString {
            get {
                return ResourceManager.GetString("TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thief.
        /// </summary>
        internal static string Thief {
            get {
                return ResourceManager.GetString("Thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each other player reveals the top 2 cards of his deck.\nIf they revealed any Treasure cards, they trash one of them that you choose.\nYou may gain any or all of these trashed cards.\nThey discard the other revealed cards..
        /// </summary>
        internal static string ThiefDesc {
            get {
                return ResourceManager.GetString("ThiefDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  revealed a .
        /// </summary>
        internal static string ThiefMsg1 {
            get {
                return ResourceManager.GetString("ThiefMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from the top of their deck..
        /// </summary>
        internal static string ThiefMsg2 {
            get {
                return ResourceManager.GetString("ThiefMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throne Room.
        /// </summary>
        internal static string ThroneRoom {
            get {
                return ResourceManager.GetString("ThroneRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose and Action card in your hand. \nPlay it twice.
        /// </summary>
        internal static string ThroneRoomDesc {
            get {
                return ResourceManager.GetString("ThroneRoomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was a tie!.
        /// </summary>
        internal static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        internal static string TypeString0 {
            get {
                return ResourceManager.GetString("TypeString0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure.
        /// </summary>
        internal static string TypeString1 {
            get {
                return ResourceManager.GetString("TypeString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string TypeString2 {
            get {
                return ResourceManager.GetString("TypeString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action - Attack.
        /// </summary>
        internal static string TypeString3 {
            get {
                return ResourceManager.GetString("TypeString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action - Reaction.
        /// </summary>
        internal static string TypeString4 {
            get {
                return ResourceManager.GetString("TypeString4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  had .
        /// </summary>
        internal static string VictPts1 {
            get {
                return ResourceManager.GetString("VictPts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  victory points.\n.
        /// </summary>
        internal static string VictPts2 {
            get {
                return ResourceManager.GetString("VictPts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        internal static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Card\n+2 Actions.
        /// </summary>
        internal static string VillageDesc {
            get {
                return ResourceManager.GetString("VillageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was a remodel. Setting it to trash the next card..
        /// </summary>
        internal static string WasRemodel {
            get {
                return ResourceManager.GetString("WasRemodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witch.
        /// </summary>
        internal static string Witch {
            get {
                return ResourceManager.GetString("Witch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Cards.\nEach other player gains a Curse card..
        /// </summary>
        internal static string WitchDesc {
            get {
                return ResourceManager.GetString("WitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woodcutter.
        /// </summary>
        internal static string Woodcutter {
            get {
                return ResourceManager.GetString("Woodcutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Buy\n+2 Currencys.
        /// </summary>
        internal static string WoodcutterDesc {
            get {
                return ResourceManager.GetString("WoodcutterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        internal static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain a card costing up to 4 Currency.
        /// </summary>
        internal static string WorkshopDesc {
            get {
                return ResourceManager.GetString("WorkshopDesc", resourceCulture);
            }
        }
    }
}
